# RomanAC Config
# by Creeper215
# IMPORTANT: vl-reset-time works by MINUTES

violation-settings:
  ban-vl: 60
  kick-vl: 60
  setback-vl: 3
  alert-vl: 10
  vl-reset-time: 1

punishments:
  ban-command: "ban %player_name% 30d"
  kick-message: "§cKicked out for possibly cheating [AntiCheat]"

messages:
  prefix: "&7[&4&lR★AC&7]"
  alert-message: "%player_name% potrebbe star utilizzando %roman_check% Type: %roman_type% VL: %roman_vl%"
  vl-reset-message: "&6Tutte le &aviolazioni&6 di tutti i &cgiocatori&6 sono state &bresettate"

checks:
  combat:
    aura:
      a: true
  movement:
    groundspoof: true
  test-1: false
  test-2: false
