# RomanAC Config
# by Creeper215
# IMPORTANT: vl-reset-time works by MINUTES, same thing for banwave-time
# Punishments: "ban", "kick", "none"

violation-settings:
  ban-vl: 60
  kick-vl: 60
  setback-vl: 3
  attack-mitigation-vl: 50
  alert-vl: 10
  vl-reset-time: 1

banwave-settings:
  banwave-vl: 250
  banwave-time: 1
  banwave-type: "ban"

mitigation:
  attack-reduce-factor: 3

punishments:
  ban-command: "ban %player_name% 30d"
  kick-message: "§cKicked out for possibly cheating [AntiCheat]"

messages:
  prefix: "&7[&4&lR★AC&7]"
  alert-message: "%player_name% potrebbe star utilizzando %roman_check% Type: %roman_type% VL: %roman_vl%"
  vl-reset-message: "&6Tutte le &aviolazioni&6 di tutti i &cgiocatori&6 sono state &bresettate"
  subscribed: "&cYou are now subscribed to Roman alerts"
  unsubscribed: "&cYou aren't more subscribed to Roman alerts"

checks:
  combat:
    aura:
      a: true
      b: true
  movement:
    groundspoof: true
    punishment: "ban"
  scaffold:
    b: true
    c: true
    d: true
    f: true
    punishment: "kick"
  test-1: false
  test-2: false
