name: RomanAC
version: '1.0-SNAPSHOT'
main: it.creeper.roman.Roman
api-version: '1.8.8'
description: pizza anticheat frfr
softdepend: [PlaceholderAPI]
commands:
  roman:
    description: General plugin command