# RomanAC Config
# by Creeper215
# IMPORTANT: vl-reset-time works by MINUTES

violation-settings:
  ban-vl: 60
  kick-vl: 60
  setback-vl: 3
  alert-vl: 10
  vl-reset-time: 1

messages:
  prefix: "&7[&4&lR★AC&7]"
  alert-message: "%player_name% potrebbe star utilizzando %roman_check% Type: %roman_type% VL: %roman_vl%"
  vl-reset-message: "&6Tutte le &aviolazioni&6 di tutti i &cgiocatori&6 sono state &bresettate"